### ISSUE TITLE
Install from npm no "succeedWithoutToken"

### ISSUE THREAD

**Issue by newplayer** [adcentury/socketio-jwt-auth#10]
I Install the module from the npm and it's seems like the 0.0.5 version, but the succeedWithoutToken parameter is not working.
I look in to the code, ands it's look like something old. There is no handling of the succeedWithoutToken parameter.

**Comment by adcentury** [comment]
@newplayer I have just published the latest version (which is 0.0.6) to npm. You can try it now.

**Comment by newplayer** [comment]
Thanks, it's seems to be working now
