### ISSUE TITLE
Plans for project?

### ISSUE THREAD

**Issue by rmharrison** [adcentury/socketio-jwt-auth#12]
@adcentury In light of Auth0 stopping support for their socketio-jwt (https://github.com/auth0-community/socketio-jwt/issues/131) library, what were your plans for this project going forward?

Specifically...
- Badges
  * CI
  * Code coverage / Code Climate
- Dependency updates
  * socket.io v2

**Comment by adcentury** [comment]
@rmharrison I'm happy to add features and update dependency for this project. But it may take a long time for me to start this. (not before November). So any PR or Issue for these features is welcomed.

**Comment by adcentury** [comment]
travis ci and coverall have been integrated. #14 #15

**Comment by adcentury** [comment]
support for socket.io v2 is not in plan right now.
