### ISSUE TITLE
JWT sent via query params

### ISSUE THREAD

**Issue by Igor-Lopes** [adcentury/socketio-jwt-auth#13]
It's a terrible idea to have JWT sent via query params. Urls can be logged, cached and tracked.

**Comment by adcentury** [comment]
Is there any better idea for that ? Thanks.

**Comment by vladikus10** [comment]
@adcentury Socket.IO supports headers, which should be encrypted if you are using HTTPS. I believe Socket.IO always starts with long-polling, so the headers should always be present on connection.

**EDIT** After another look at the docs, it seems that `extraHeaders` only work if you are using the NodeJS client socket.io. However, it's still would be nice to have that option and use query params as a worst case alternative.

**Comment by jasonk** [comment]
Note that if you are using HTTPS then the URL is also encrypted, so this is really a non-issue
