### ISSUE TITLE
socketio-jwt-auth is preventing my electron app to connect socket.io server 

### ISSUE THREAD

**Issue by Akumzy** [adcentury/socketio-jwt-auth#16]
I Can't connect to server from an electron app this error kept on popping up
```Can't connect to server from an electron app```
socketio-jwt-auth is preventing my electron socket.io-client to connect.

is has the exact config with the web config which works perfectly

**Comment by adcentury** [comment]
It may not be the issue of `socket-jwt-auth`. Cause it's just a socket.io middleware and works fine in any environment that `socket.io` does.

Can you give me some more info about this issue ? (Such as error stack or logs)

**Comment by Akumzy** [comment]
Yeah is coming from jwt-simple which is logging `Signature verification failed` 
`var signingInput = [headerSeg, payloadSeg].join('.');
    if (!verify(signingInput, key, signingMethod, signingType, signatureSeg)) {
      throw new Error('Signature verification failed');
    }`

**Comment by Akumzy** [comment]
And the electron socket.io-client is using ws instead of http

**Comment by Akumzy** [comment]
@adcentury please can you help me out here
