### ISSUE TITLE
Connecting as a guest, how to supply login credentials to socketio, after login?

### ISSUE THREAD

**Issue by moparlakci** [adcentury/socketio-jwt-auth#17]
My case is the following

When a user connects as a guest, before supplying login credentials. He gets connected thats nice!

On the client side when I successfully login to the application. The returned JWT is being saved in localStorage. But the socket doesn't know anything about that.

In order to fix this I need to refresh the page to use the token from localStorage from my login to send to the socket server.

I hacked the code a little in my authentication function... to let the socket know that the user is connected 

`socket.request.user = {...person, logged_in: true };`

Do you have a better method or a real world example for this?

Thanks.

**Comment by adcentury** [comment]
@moparlakci After user logged, I think you should create a new connection for this session.

If you have better idea, please create a PR for it. Thanks.
