### ISSUE TITLE
Not enough or too many segments

### ISSUE THREAD

**Issue by Pedroxam** [adcentury/socketio-jwt-auth#29]
Have Problem, its good for you to make a simple test on a place like stackblitz.
because i try anyway and this package not work !

```
// Server Side
const express = require('express');
const server = express();
const app = require('http').createServer(server);
const io = require('socket.io')(app);
var jwtAuth = require('socketio-jwt-auth');

io.use(jwtAuth.authenticate({
  secret: 'your_secret',
  algorithm: 'HS256',
  succeedWithoutToken: true
}, function(payload, done){
// This part is never work
  console.log('work')
}
));

io.on('connection', function(socket) {
  socket.emit('success', {
    message: 'success logged in!',
    user: socket.request.user
  });
});

//Client Side

const socket = io('ws://127.0.0.1:3002', { query: `auth_token=x`});
`
  socket.on('error', function(err) {
    console.log(err)
  });

  socket.on('success', function(data) {
    console.log(data);
  })
```

Response

![image](https://user-images.githubusercontent.com/6213778/129219512-70c791e2-16a1-47bf-95bd-5a5fa030544d.png)

**Comment by adcentury** [comment]
@Pedroxam The auth_token must be a valid jwt token. In your case, you should replace `auth_token=x` to `auth_token=THE_VALID_JWT_TOKEN`. Also notice that if you are using socket.io v3, you must use `auth` key instead of `query`. See https://github.com/adcentury/socketio-jwt-auth#client-side
