### ISSUE TITLE
Not handling token expiration

### ISSUE THREAD

**Issue by holtc** [adcentury/socketio-jwt-auth#9]
In my token, I set the expiration to be 60 minutes.  However, the authenticate() method continues to treat the token as valid after expiration.  Is there something I am doing wrong, or does this library not support token expiration?

**Comment by vaggeliskls** [comment]
I faced this problem too. In order to fix this you have to check the token expiration in authenticate() middleware. 

 
          let nowDaytime=Math.floor(Date.now() / 1000) ;
          if(payload.exp<nowDaytime)
          {
              // return fail with an error message
              return done(null, false, 'token expired');
          }
          else
          {
              return done(null, user);
          }

**Comment by adcentury** [comment]
@holtc Hi, have you fixed it by @vaggeliskls 's method? If so I will close this issue.

**Comment by adcentury** [comment]
Close due to no further response.
